### ISSUE TITLE
Error after update to 1.0.8

### ISSUE THREAD

**Issue by alexandruantonica** [roblav96/nativescript-onesignal#39]
After I update the plugin to 1.0.8 I have this error when I run `tns run android`. 
@roblav96 Seems like your postinstall script have some errors. 

```
Error: Cannot find module '/...app_folder/node_modules/postinstall-hooks.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
(node:25010) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
```

Let me know if you need more info.

**Comment by jkasten2** [comment]
@alexandruantonica Can you give this fork a try?
https://github.com/OneSignal/nativescript-onesignal

This one has the fork has the install hooks removed so it should get you past this error.

**Comment by alexandruantonica** [comment]
@jkasten2 How can I install a plugin for Nativescript from Github? 
I've tried `npm i --save OneSignal/nativescript-onesignal` but the code is not compiled and I don't have any `index.js`and the app throw an error that couldn't find `nativescript-onesignal`. 

Thanks ;)

**Comment by SalehMahmood** [comment]
Having the same issue

**Comment by MopheusDG** [comment]
Same here...

**Comment by uzarsalan** [comment]
Same issue
